name: simple_slash_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  custom_refresh_indicator: ^3.0.0
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  infinite_scroll_pagination: ^4.0.0
  like_button: ^2.0.5
  logger: ^2.1.0
  numeral: ^3.0.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/noto_sans/
    - assets/fonts/Roboto/
    - assets/images/
